---

binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptimerobot
# Radarr
  - platform: command_line
    name: "Radarr Online"
    command: curl 192.168.1.190:7878 > /dev/null && echo "Online" || echo "Offline"
    scan_interval: 90
    value_template: "{{ value }}"