---

binary_sensor:
  - platform: uptimerobot
    api_key: !secret uptimerobot
# Radarr
  - platform: command_line
    name: "Radarr Online"
    command: curl 192.168.1.190:7878 > /dev/null && echo on || echo off
    scan_interval: 90
    payload_on: "on"
    payload_off: "off"