#Copy from here#
#Start of dwains-theme necesary code#
homeassistant:
  # If you want to customize entries with friendly_name or custom icon.
  # Read more here: https://www.home-assistant.io/docs/configuration/customizing-devices/
  # Uncomment line below and create file customize.yaml or edit it
  # customize: !include customize.yaml

  # Below is link to packages folder for Dwains Theme
  # Check out user-package-sample in your downloaded folder for an example
  # to create a own package folder
  packages: !include_dir_named packages/ # Comment this whole line if you want to disable Dwains Theme

  # If you had any important strings before in homeassistant: place them back here below
  # 
#End of dwains-theme necesary code#
#Copy till here#

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  service_account: !include Home Assistant-2f7fd9e17963.json
  report_state: true
  exposed_domains:
    - switch
    - light
    - group

# SSL
http:
  base_url: !secret base_url

input_text:
  card_containers:
    initial: Containers
  software_version:
    initial: Version

ziggonext:
  username: !secret ziggonext_username
  password: !secret ziggonext_password
  country_code: nl