# TEST

sensor:
  - platform: airvisual
    api_key: !secret airvisual_api
    monitored_conditions:
      - us
    show_on_map: false
    scan_interval: 300
    latitude: !secret home_latitude
    longitude: !secret home_longitude