sensor:
# Parity Disk Temperature
  - platform: snmp
    name: 'UnRAID PARITY Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.1
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (1) Temperature
  - platform: snmp
    name: 'UnRAID DISK1 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.2
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (2) Temperature
  - platform: snmp
    name: 'UnRAID DISK2 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.3
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (3) Temperature
  - platform: snmp
    name: 'UnRAID DISK3 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.4
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (4) Temperature
  - platform: snmp
    name: 'UnRAID DISK4 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.5
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (5) Temperature
  - platform: snmp
    name: 'UnRAID DISK5 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.6
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (6) Temperature
  - platform: snmp
    name: 'UnRAID DISK6 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.7
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# HDD Disk (7) Temperature
  - platform: snmp
    name: 'UnRAID DISK7 Temperature'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.8
    accept_errors: true
    value_template: >
       {{ value | regex_findall_index("(\d+)$") }}
    unit_of_measurement: '°C'

# Upload LAN0
  - platform: snmp
    name: 'UnRAID LAN0 Upload'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.11
    accept_errors: true
    unit_of_measurement: "Kbps"
    value_template: '{{((value | float ) / 1000000 ) | round(2) }}'

# Upload LAN1
  - platform: snmp
    name: 'UnRAID LAN1 Upload'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.12
    accept_errors: true
    unit_of_measurement: "Kbps"
    value_template: '{{((value | float ) / 1000000 ) | round(2) }}'

# Upload 10Gbe
  - platform: snmp
    name: 'UnRAID 10Gbe Upload'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.13
    accept_errors: true
    unit_of_measurement: "Kbps"
    value_template: '{{((value | float ) / 1000000 ) | round(2) }}'

# Download LAN0
  - platform: snmp
    name: 'UnRAID LAN0 Download'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.11
    accept_errors: true
    unit_of_measurement: "Kbps"
    value_template: '{{((value | float ) / 1000000 ) | round(2) }}'

# Download LAN1
  - platform: snmp
    name: 'UnRAID LAN1 Download'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.12
    accept_errors: true
    unit_of_measurement: "Kbps"
    value_template: '{{((value | float ) / 1000000 ) | round(2) }}'

# Download 10Gbe
  - platform: snmp
    name: 'UnRAID 10Gbe Download'
    host: !secret unraid_ip
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.13
    accept_errors: true
    unit_of_measurement: "Kbps"
    value_template: '{{((value | float ) / 1000000 ) | round(2) }}'