global:
   language: nl
   weather: weather.dark_sky
   outside_temperature: sensor.dark_sky_temperature
   outside_humidity: sensor.dark_sky_humidity
   alarm: alarm_control_panel.home_alarm
   inside_temperature: sensor.multi_sensor_living_room_3