automation:
  - id: '233202001'
    alias: '[ Notificatie ] Adguard Docker is Offline'
    description: 'Adguard docker is offline op de unraid server. '
    trigger:
    - device_id: no233202001
      domain: switch
      entity_id: switch.tower_docker_adguardhome
      platform: device
      type: turned_off
    condition: []
    action:
    - data:
        message: Adguard Docker is offline!
      service: notify.notify
