automation:
  - id: '233202005'
    alias: '[ Notificatie ] Glances Docker is Offline'
    description: 'Glances docker is offline op de unraid server. '
    trigger:
    - device_id: no233202005
      domain: switch
      entity_id: switch.tower_docker_glances
      platform: device
      type: turned_off
    condition: []
    action:
    - data:
        message: Glances Docker is offline!
      service: notify.notify
